volumes:
  postgres-data:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        - ./.env

    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db
    ports:
      - "8080:8080"


  db:
    image: postgres:17.6-trixie
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      -  ../database/:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./.env
    ports:
      - "5432:5432"
