name: Go

on: [push, pull_request]

env:
  GO-VERSION: 1.25.0

jobs:
  build:

    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO-VERSION }}
          cache-dependency-path: go.sum
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Run tests
        run: go test -v ./...
