name: Payout Management System

on: [push, pull_request]

jobs:
  format:
    name: Check format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: test -z "$(gofmt -l .)"

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
  test:

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache-dependency-path: go.sum
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Run tests
        run: go test -v ./...
