name: Payout Management System

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache-dependency-path: go.sum

  format:
    name: Check format
    runs-on: ubuntu-24.04
    needs: setup
    steps:
      - run: test -z "$(gofmt -l .)"

  lint:
    runs-on: ubuntu-24.04
    needs: format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache-dependency-path: go.sum
      - name: Run linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0

  test:
    runs-on: ubuntu-24.04
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test -v ./...
