name: Go

on:
  push:
    branches:
      - expense
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache-dependency-path: go.sum
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test -v ./...
